workflows:
  pdf_inference:
    name: pdf_inference
    description: A workflow for PDF inference
    agents:
      - pdf_parser
    input_topics:
      - pdf_parser/input
    output_topics:
      - pdf_parser/output

  nn_train_from_sheet:
    name: nn_train_from_sheet
    description: A workflow for training a neural network from a sheet
    agents:
      - sheet_parser
      - nn_trainer
    input_topics:
      - sheet_parser/input
      - nn_trainer/input
    output_topics:
      - nn_trainer/input
      - nn_trainer/output

  chatbot:
    name: chatbot
    description: A workflow for chatbot conversation
    agents:
      - chatbot
    input_topics:
      - chatbot/input
    output_topics:
      - chatbot/output
