name: ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24.0,<2.0.0
  - pandas>=2.2.3
  - streamlit=1.37.1
  - pip:
    # PyTorch with ROCm support
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2

    # Core ML libraries
    - transformers==4.36.0
    - datasets==3.2.0
    - accelerate==0.34.0
    - optimum==1.16.0
    - safetensors==0.5.2
    - einops==0.8.0
    - auto-gptq==0.7.1
    - peft==0.14.0
    - bitsandbytes==0.41.0

    # Audio processing
    - librosa==0.10.2
    - soundfile==0.13.0
    - sounddevice==0.5.1

    # Text processing and metrics
    - nltk==3.8.1
    - rouge==1.0.1
    - evaluate==0.4.3
    - tokenizers>=0.14,<0.19  # Compatible with transformers
    - sentencepiece==0.2.0

    # LLM and chat
    - ollama==0.4.3
    - huggingface-hub==0.27.1

    # Utilities
    - tqdm==4.67.1
    - scipy==1.13.1
    - pillow==11.0.0
    - scikit-learn==1.5.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - filelock==3.13.1
    - packaging==24.2
    - regex==2024.11.6
    - typing-extensions==4.12.2
