FROM ubuntu:22.04

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-distutils \
    python3-pip \
    curl \
    git \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Update pip
RUN pip install --upgrade pip

# Install ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copy code to inside the image
COPY requirements.txt /app/requirements.txt
RUN pip install setuptools==75.1.0
RUN pip install --no-cache-dir --no-deps -r /app/requirements.txt

# Set the ollama models custom directory
COPY ollama_models /app/ollama_models
ENV OLLAMA_MODELS="/app/ollama_models"

# Copy interesting folders and app file
COPY ai_apis /app/ai_apis
COPY apps/chat_app.py /app/chat_app.py

# Set the command to run the chat application
EXPOSE 8501
CMD OLLAMA_ACCELERATE=gpu ollama serve & streamlit run --server.port=8501 --server.address=0.0.0.0 chat_app.py
