FROM ubuntu:22.04

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-distutils \
    python3-pip \
    curl \
    git \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Update pip
RUN pip install --upgrade pip

# Install ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copy code to inside the image
RUN pip install setuptools==75.1.0
COPY requirements/requirements_chatbot.txt /app/requirements_chatbot.txt
RUN pip install --no-cache-dir --timeout=100 --retries=100 -r requirements_chatbot.txt

# Set the ollama models custom directory
COPY ollama_models /app/ollama_models
ENV OLLAMA_MODELS="/app/ollama_models"

# Copy interesting folders and app file
COPY ai_apis/chat_with_history.py /app/ai_apis/chat_with_history.py
COPY agents/chatbot_agent.py /app/agents/chatbot_agent.py
COPY agents/start_chatbot_docker.sh /app/agents/start_chatbot_docker.sh
RUN chmod +x /app/agents/start_chatbot_docker.sh

# Expose the MQTT port
EXPOSE 1883

# Set the command to run the agent as a module
ENTRYPOINT ["/app/agents/start_chatbot_docker.sh"]
