FROM ubuntu:22.04

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-distutils \
    python3-pip \
    curl \
    git \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Install docker-cli
RUN apt-get update && apt-get install -y docker-cli

# Update pip
RUN pip install --upgrade pip

# Install pip dependencies
RUN pip install --no-cache-dir flask flask_cors pydantic

# Copy interesting folders and app file
COPY rest_apis/start_ai_assistant_agent_docker.py /app/start_ai_assistant_agent_docker.py
COPY rest_apis/common.py /app/common.py
RUN chmod +x /app/start_ai_assistant_agent_docker.py /app/common.py

# Expose the REST API port
EXPOSE 8002

# Set the command to run the REST API
CMD ["/app/start_ai_assistant_agent_docker.py"]
