pdfs:
  - "/home/vini/Downloads/Passagem - SP - Setembro.pdf"
  - "/home/vini/Downloads/Hotel SP Setembro 2025.pdf"
  - "/home/vini/Downloads/box 31 servicos.pdf"
  - "/home/vini/Downloads/contrato natal.pdf"
  - "/home/vini/Downloads/Relatório_de_Atividades___Integração_de_Dados.pdf"
  - "/home/vini/Downloads/APEX and SOLIX G3 Operations Manual.pdf"

urls:
  - "https://www.in.gov.br/en/web/dou/-/resolucao-normativa-aneel-n-1.125-de-27-de-maio-de-2025-634339148"
